import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import {
  GlassCard,
  PageHeader,
  SectionTitle,
  Chip,
} from "@/components/premium";
import {
  Target,
  TrendingUp,
  Package,
  Users,
  Layers,
  Sparkles,
  ArrowRight,
  Search,
  RefreshCw,
  Database,
  Zap,
} from "lucide-react";
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
} from "recharts";
import { tooltipStyle } from "./index";
import { useRecommendations } from "@/hooks/use-recommendations";

export const Route = createFileRoute("/recommendations")({
  component: RecommendationIntelligence,
});

const pipeline = [
  {
    name: "Popularity",
    icon: TrendingUp,
    desc: "Global winners baseline",
  },
  {
    name: "Collaborative",
    icon: Users,
    desc: "User × item interaction patterns",
  },
  {
    name: "Segment-Aware",
    icon: Layers,
    desc: "Behavioral cohort ranking",
  },
  {
    name: "Hybrid Ranker",
    icon: Sparkles,
    desc: "Combined recommendation strategy",
  },
];

function recommendationReason(source: string) {
  switch (source) {
    case "collaborative":
      return "Frequently interacted with alongside items already in this customer's history (item co-occurrence).";
    case "segment":
      return "Popular among customers in the same behavioral segment.";
    case "popularity":
      return "One of the most-purchased items across the RetailRocket catalog.";
    default:
      return "Selected by the hybrid recommendation ranker for this customer.";
  }
}

function RecommendationIntelligence() {
  const [visitorInput, setVisitorInput] = useState("1150086");
  const [visitorId, setVisitorId] = useState<number | null>(1150086);

  const { data, isLoading, isError, error, refetch } =
    useRecommendations(visitorId);

  const sourceDistribution = useMemo(() => {
    if (!data?.recommendations) return [];

    const counts: Record<string, number> = {};

    for (const rec of data.recommendations) {
      const source = rec.tag || rec.source;
      counts[source] = (counts[source] || 0) + 1;
    }

    return Object.entries(counts).map(([s, v]) => ({
      s,
      v,
    }));
  }, [data]);

  const handleSearch = () => {
    const parsed = Number(visitorInput.trim());

    if (!Number.isInteger(parsed) || parsed <= 0) {
      return;
    }

    setVisitorId(parsed);
  };

  const handleKeyDown = (
    event: React.KeyboardEvent<HTMLInputElement>
  ) => {
    if (event.key === "Enter") {
      handleSearch();
    }
  };

  return (
    <div className="px-6 md:px-10 py-8 max-w-[1600px] mx-auto">
      <PageHeader
        eyebrow="Recommendation Intelligence"
        title="Hybrid ranker, in production."
        description="Real RetailRocket recommendations generated by the project's Hybrid Recommender."
        actions={
          <Chip tone="primary">
            <Target className="w-3 h-3" />
            RetailRocket Live
          </Chip>
        }
      />

      {/* Customer selector */}
      <GlassCard className="p-5 mt-8">
        <div className="flex flex-col lg:flex-row lg:items-end gap-4">
          <div className="flex-1">
            <div className="text-[10px] uppercase tracking-widest text-muted-foreground mb-2">
              Customer / Digital Twin
            </div>

            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />

              <input
                value={visitorInput}
                onChange={(e) => setVisitorInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Enter customer ID, e.g. 1150086"
                className="w-full h-11 rounded-xl bg-white/[0.03] border border-white/10 pl-10 pr-4 text-sm outline-none focus:border-primary/50 transition"
              />
            </div>
          </div>

          <button
            type="button"
            onClick={handleSearch}
            className="h-11 px-5 rounded-xl bg-[image:var(--gradient-primary)] text-background text-sm font-semibold flex items-center justify-center gap-2 hover:opacity-90 transition"
          >
            <Search className="w-4 h-4" />
            Load Recommendations
          </button>

          <button
            type="button"
            onClick={() => refetch()}
            disabled={isLoading}
            className="h-11 px-4 rounded-xl glass border border-white/10 flex items-center justify-center gap-2 text-sm hover:border-white/20 transition disabled:opacity-50"
          >
            <RefreshCw
              className={`w-4 h-4 ${
                isLoading ? "animate-spin" : ""
              }`}
            />
            Refresh
          </button>
        </div>
      </GlassCard>

      {/* Loading */}
      {isLoading && (
        <GlassCard className="p-8 mt-4">
          <div className="flex items-center justify-center gap-3 text-muted-foreground">
            <RefreshCw className="w-5 h-5 animate-spin" />
            Loading real recommendation data...
          </div>
        </GlassCard>
      )}

      {/* Error */}
      {isError && (
        <GlassCard className="p-8 mt-4">
          <div className="text-center">
            <div className="text-red-400 text-sm font-semibold">
              Unable to load recommendations
            </div>

            <div className="text-xs text-muted-foreground mt-2">
              {error instanceof Error
                ? error.message
                : "Customer may not exist."}
            </div>
          </div>
        </GlassCard>
      )}

      {/* Main content */}
      {data && !isLoading && !isError && (
        <>
          {/* Customer summary */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4">
            <GlassCard className="p-5">
              <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
                Customer
              </div>
              <div className="text-xl font-semibold mt-2">
                {data.visitorId}
              </div>
              <div className="text-[11px] text-muted-foreground mt-1">
                Raw ID {data.rawId}
              </div>
            </GlassCard>

            <GlassCard className="p-5">
              <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
                Segment
              </div>
              <div className="text-xl font-semibold mt-2">
                {data.segment}
              </div>
              <div className="text-[11px] text-muted-foreground mt-1">
                Behavioral cohort
              </div>
            </GlassCard>

            <GlassCard className="p-5">
              <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
                Buy Probability
              </div>
              <div className="text-xl font-semibold mt-2">
                {(data.buyProbability * 100).toFixed(2)}%
              </div>
              <div className="text-[11px] text-muted-foreground mt-1">
                Module 3 model output
              </div>
            </GlassCard>

            <GlassCard className="p-5">
              <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
                Interactions
              </div>
              <div className="text-xl font-semibold mt-2">
                {data.interactionCount.toLocaleString()}
              </div>
              <div className="text-[11px] text-muted-foreground mt-1">
                Recommendation history
              </div>
            </GlassCard>
          </div>

          {/* Strategy banner */}
          <GlassCard className="p-5 mt-4" glow>
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div>
                <div className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-primary" />
                  <span className="text-sm font-semibold">
                    Active Recommendation Strategy
                  </span>
                </div>

                <div className="text-2xl font-semibold mt-2">
                  {data.strategy}
                </div>

                <div className="text-xs text-muted-foreground mt-1">
                  Strategy selected from the customer's real behavioral state.
                </div>
              </div>

              <div className="flex flex-wrap gap-2">
                <Chip tone="primary">
                  <Database className="w-3 h-3" />
                  {data.dataSource}
                </Chip>

                <Chip tone="violet">
                  {data.recommendations.length} ranked items
                </Chip>
              </div>
            </div>
          </GlassCard>

          {/* Pipeline */}
          <GlassCard className="p-6 mt-4">
            <SectionTitle
              title="Recommendation Pipeline"
              subtitle="From raw signals to ranked slate"
            />

            <div className="flex flex-wrap items-stretch gap-3">
              {pipeline.map((p, i) => (
                <div
                  key={p.name}
                  className="flex items-center gap-3 flex-1 min-w-[200px]"
                >
                  <div className="flex-1 p-4 rounded-xl glass hover:border-white/15 transition group">
                    <div className="flex items-center gap-2 mb-2">
                      <div className="w-8 h-8 rounded-lg bg-[image:var(--gradient-primary)] grid place-items-center">
                        <p.icon className="w-4 h-4 text-background" />
                      </div>

                      <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
                        Stage {i + 1}
                      </div>
                    </div>

                    <div className="text-sm font-semibold">
                      {p.name}
                    </div>

                    <div className="text-[11px] text-muted-foreground mt-1">
                      {p.desc}
                    </div>
                  </div>

                  {i < pipeline.length - 1 && (
                    <ArrowRight className="w-4 h-4 text-muted-foreground shrink-0" />
                  )}
                </div>
              ))}
            </div>
          </GlassCard>

          {/* Recommendations + distribution */}
          <div className="grid grid-cols-1 xl:grid-cols-3 gap-4 mt-4">
            <div className="xl:col-span-2">
              <GlassCard className="p-6">
                <SectionTitle
                  title="Top Recommendations"
                  subtitle={`Real ranked slate for ${data.visitorId}`}
                />

                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {data.recommendations.map((r) => (
                    <div
                      key={`${r.rank}-${r.itemId}`}
                      className="p-4 rounded-xl glass hover:border-white/15 group transition"
                    >
                      <div className="flex items-start gap-3">
                        <div className="w-14 h-14 rounded-lg bg-gradient-to-br from-primary/25 via-violet/20 to-transparent grid place-items-center shrink-0">
                          <Package className="w-6 h-6 text-white/80" />
                        </div>

                        <div className="min-w-0 flex-1">
                          <div className="flex items-center justify-between gap-2">
                            <div className="text-[13px] font-semibold truncate">
                              {r.itemId}
                            </div>

                            <div className="text-[11px] font-mono text-muted-foreground">
                              #{r.rank}
                            </div>
                          </div>

                          <div className="flex items-center gap-2 mt-1">
                            <Chip tone="violet">
                              {r.tag}
                            </Chip>

                            <span className="text-[10px] text-muted-foreground">
                              {r.source}
                            </span>
                          </div>

                          <div className="text-[11px] text-muted-foreground mt-2 leading-relaxed">
                            {recommendationReason(r.source)}
                          </div>

                          <div className="mt-2 h-1 rounded-full bg-white/5 overflow-hidden">
                            <div
                              className="h-full bg-[image:var(--gradient-primary)]"
                              style={{
                                width: `${Math.max(
                                  10,
                                  100 - (r.rank - 1) * 8
                                )}%`,
                              }}
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Catalog note */}
                <div className="mt-5 p-4 rounded-xl bg-white/[0.02] border border-white/5">
                  <div className="flex items-start gap-3">
                    <Database className="w-4 h-4 text-muted-foreground mt-0.5 shrink-0" />

                    <div>
                      <div className="text-[11px] font-semibold">
                        Catalog limitation
                      </div>

                      <div className="text-[11px] text-muted-foreground mt-1 leading-relaxed">
                        {data.catalogNote}
                      </div>
                    </div>
                  </div>
                </div>
              </GlassCard>
            </div>

            <div className="space-y-4">
              <GlassCard className="p-6" glow>
                <SectionTitle
                  title="Recommendation Mix"
                  subtitle="Sources in this customer's ranked slate"
                />

                <div className="h-[240px]">
                  {sourceDistribution.length > 0 ? (
                    <ResponsiveContainer>
                      <BarChart
                        data={sourceDistribution}
                        margin={{
                          top: 10,
                          right: 8,
                          left: -20,
                          bottom: 0,
                        }}
                        layout="vertical"
                      >
                        <CartesianGrid
                          stroke="rgba(255,255,255,0.05)"
                          horizontal={false}
                        />

                        <XAxis
                          type="number"
                          allowDecimals={false}
                          stroke="rgba(255,255,255,0.3)"
                          fontSize={10}
                          tickLine={false}
                          axisLine={false}
                        />

                        <YAxis
                          dataKey="s"
                          type="category"
                          stroke="rgba(255,255,255,0.5)"
                          fontSize={10}
                          tickLine={false}
                          axisLine={false}
                          width={85}
                        />

                        <Tooltip contentStyle={tooltipStyle} />

                        <Bar
                          dataKey="v"
                          fill="var(--violet)"
                          radius={[0, 6, 6, 0]}
                        />
                      </BarChart>
                    </ResponsiveContainer>
                  ) : (
                    <div className="h-full grid place-items-center text-xs text-muted-foreground">
                      No recommendation data.
                    </div>
                  )}
                </div>
              </GlassCard>

              <GlassCard className="p-6">
                <SectionTitle
                  title="Live Recommendation State"
                  subtitle="Real backend values"
                />

                <div className="space-y-3">
                  <StateRow
                    label="Strategy"
                    value={data.strategy}
                  />

                  <StateRow
                    label="Segment"
                    value={data.segment}
                  />

                  <StateRow
                    label="Buy probability"
                    value={`${(
                      data.buyProbability * 100
                    ).toFixed(2)}%`}
                  />

                  <StateRow
                    label="Interactions"
                    value={data.interactionCount.toLocaleString()}
                  />

                  <StateRow
                    label="Ranked items"
                    value={String(data.recommendations.length)}
                  />
                </div>
              </GlassCard>
            </div>
          </div>

          {/* Network */}
          <GlassCard className="p-6 mt-4">
            <SectionTitle
              title="User × Item Network"
              subtitle="Real recommended items for the selected customer"
              right={
                <Chip tone="primary">
                  {data.recommendations.length} ranked edges
                </Chip>
              }
            />

            <RecommendationGraph
              visitorId={data.visitorId}
              recommendations={data.recommendations}
            />
          </GlassCard>
        </>
      )}
    </div>
  );
}

function StateRow({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div className="flex items-center justify-between gap-4">
      <span className="text-[11px] text-muted-foreground">
        {label}
      </span>

      <span className="text-[12px] font-mono text-foreground">
        {value}
      </span>
    </div>
  );
}

function RecommendationGraph({
  visitorId,
  recommendations,
}: {
  visitorId: string;
  recommendations: {
    itemId: string;
    rank: number;
    source: string;
    tag: string;
  }[];
}) {
  const visibleRecommendations = recommendations.slice(0, 6);

  return (
    <div className="relative h-[320px] rounded-xl overflow-hidden bg-grid">
      <svg className="absolute inset-0 w-full h-full">
        <defs>
          <linearGradient
            id="edge"
            x1="0"
            y1="0"
            x2="1"
            y2="0"
          >
            <stop
              offset="0%"
              stopColor="var(--primary)"
              stopOpacity="0.5"
            />

            <stop
              offset="100%"
              stopColor="var(--violet)"
              stopOpacity="0.5"
            />
          </linearGradient>
        </defs>

        {visibleRecommendations.map((item, index) => {
          const y2 =
            visibleRecommendations.length === 1
              ? 160
              : 30 +
                (index * 260) /
                  (visibleRecommendations.length - 1);

          return (
            <line
              key={item.itemId}
              x1="15%"
              y1="160"
              x2="85%"
              y2={y2}
              stroke="url(#edge)"
              strokeWidth="1.5"
              opacity="0.75"
            />
          );
        })}
      </svg>

      <div className="absolute inset-0 flex justify-between items-center px-6">
        <div className="flex flex-col items-center justify-center">
          <div className="w-14 h-14 rounded-full bg-primary/20 border border-primary/40 grid place-items-center backdrop-blur-sm">
            <Users className="w-6 h-6 text-primary" />
          </div>

          <div className="text-[10px] font-mono mt-2 text-muted-foreground">
            {visitorId}
          </div>
        </div>

        <div className="flex flex-col gap-3">
          {visibleRecommendations.map((item) => (
            <div
              key={item.itemId}
              className="flex items-center gap-2"
            >
              <div className="w-10 h-10 rounded-lg bg-violet/20 border border-violet/40 grid place-items-center backdrop-blur-sm">
                <Package className="w-4 h-4 text-violet" />
              </div>

              <div className="text-[10px] font-mono text-muted-foreground w-28 truncate">
                {item.itemId}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="absolute bottom-2 left-3 text-[10px] uppercase tracking-widest text-muted-foreground">
        Customer
      </div>

      <div className="absolute bottom-2 right-3 text-[10px] uppercase tracking-widest text-muted-foreground">
        Recommended Items
      </div>
    </div>
  );
}